CONFIG_FILE: str = "config.json"
DOCKER_NAMESPACE: str = "pdfix"
DOCKER_REPOSITORY: str = "pdf-accessibility-docling"
DOCKER_IMAGE: str = f"{DOCKER_NAMESPACE}/{DOCKER_REPOSITORY}"
PERCENT_AI: float = 0.8
PERCENT_CONVERT: float = 0.1
PERCENT_RENDER: float = 0.1
PROGRESS_FIRST_STEP: int = 10  # Initialize (open document, read page count, etc.)
PROGRESS_FOURTH_STEP: int = 70  # Autotagging
PROGRESS_SECOND_STEP: int = 900  # Run AI heavy workload (+ rendering + template conversion)
PROGRESS_THIRD_STEP: int = 30  # Creating template
